language: android
jdk:
  - oraclejdk8
android:
  components:
  - platform-tools
  - tools
  - build-tools-23.0.3
  - android-22
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"  
before_script:
    - nvm install 4.2.3
    - nvm user 4.2.3
    - npm install -g grunt-cli
    - npm install
script:
    grunt build
